# Generated by Django 5.2.6 on 2025-11-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=20, unique=True)),
                ('vessel_name', models.CharField(blank=True, max_length=120, null=True)),
                ('importer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tin', models.CharField(blank=True, max_length=50, null=True)),
                ('customs_status', models.CharField(default='UNKNOWN', max_length=20)),
                ('shipping_status', models.CharField(default='UNKNOWN', max_length=20)),
                ('inspection_status', models.CharField(default='NOT_SCHEDULED', max_length=20)),
                ('logs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
