# Generated by Django 5.2.6 on 2025-11-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='container',
            name='cargo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='cargo_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='customs_duty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='customs_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='document_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='importer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='overall_status',
            field=models.CharField(choices=[('PENDING_VALIDATION', 'Pending Validation'), ('VALIDATED', 'Validated'), ('PENDING_CUSTOMS', 'Pending Customs'), ('CUSTOMS_CLEARED', 'Customs Cleared'), ('PENDING_INSPECTION', 'Pending Inspection'), ('INSPECTION_PASSED', 'Inspection Passed'), ('RELEASED', 'Released'), ('FAILED', 'Failed')], default='PENDING_VALIDATION', max_length=30),
        ),
        migrations.AddField(
            model_name='container',
            name='port_of_discharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='port_of_loading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='customs_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT_REQUIRED', 'Payment Required'), ('PAID', 'Paid'), ('CLEARED', 'Cleared'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='container',
            name='inspection_status',
            field=models.CharField(choices=[('NOT_SCHEDULED', 'Not Scheduled'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='NOT_SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='container',
            name='logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='container',
            name='shipping_status',
            field=models.CharField(choices=[('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('DISCHARGED', 'Discharged'), ('READY_FOR_PICKUP', 'Ready for Pickup')], default='IN_TRANSIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='container',
            name='tin',
            field=models.CharField(blank=True, help_text='Tax Identification Number', max_length=50, null=True),
        ),
    ]
